### ISSUE TITLE
Planteamiento del Problema 

### ISSUE THREAD

**Issue by VeronicaMoise** [crismarort/Git_DGP_CM#1]
Hola Cristina:

Como he podido observar no estamos de acuerdo en los cambios realizados de algunas definiciones de tu repositorio. A continuación te planteo mis sugerencias.

En la primera definición n_elementos_pos(l)  da igual cual elegir, ya que en mi caso, me sale el doble de elementos positivos de una lista dada y en tu caso da el triple. Yo sugiero arreglar este conflicto quedándonos con el 2.

En la siguiente definición al ver que tu resultado es mejor que el mío sugiero quedarnos con el tuyo y así realizar un cambio en la rama original.

Como las dos estamos de acuerdo en el cálculo de divisores, es decir, preferimos calcular los divisores de un número excepto este y su mitad. 

En la última definición estamos de acuerdo en no realizar ningún cambio.

Saludos cordiales.
Espero tu respuesta.

**Comment by crismarort** [comment]
Hola Verónica,

en relación a tu propuesta de cambios te propongo lo siguiente:

Dado que he estado revisando detenidamente el repositorio podría decirte que estoy de acuerdo con tus propuesta de cambios por lo que podemos dejarlo así. Además, acepto pull requests.

Gracias por tu tiempo,

Un saludo,
Cristina.
